-- 20251130_base_schema.sql
-- Foundational tables that pre-date the migration system.
-- All tables use CREATE TABLE IF NOT EXISTS so this migration is safe
-- to apply against an existing database where these tables already exist.
-- Columns added by later ALTER TABLE migrations are NOT included here.

BEGIN;

-- Core schema (used by migrations from 20251226 onward)
CREATE SCHEMA IF NOT EXISTS core;

-- 1. organizations — no dependencies
CREATE TABLE IF NOT EXISTS public.organizations (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    TEXT NOT NULL,
    slug    TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    -- tenant_uuid added by 20260513_s1_4_export_delete_tokens.sql
);

-- 2. asset_types — no dependencies
CREATE TABLE IF NOT EXISTS public.asset_types (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       TEXT NOT NULL,
    name       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. bases — depends on organizations
CREATE TABLE IF NOT EXISTS public.bases (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    lon        DOUBLE PRECISION NOT NULL,
    lat        DOUBLE PRECISION NOT NULL,
    address    TEXT,
    active     BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    org_id     BIGINT NOT NULL REFERENCES public.organizations(id)
);

-- 4. assets — depends on organizations, asset_types
CREATE TABLE IF NOT EXISTS public.assets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id        BIGINT NOT NULL REFERENCES public.organizations(id),
    asset_type_id BIGINT NOT NULL REFERENCES public.asset_types(id),
    seed_key      TEXT NOT NULL,
    lon           DOUBLE PRECISION,
    lat           DOUBLE PRECISION,
    display_name  TEXT,
    active        BOOLEAN NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    -- attributes, external_id added by 20260512_tier8_asset_abstraction.sql
);

-- 5. route_pools — depends on organizations, bases
CREATE TABLE IF NOT EXISTS public.route_pools (
    id                  TEXT PRIMARY KEY,
    label               TEXT NOT NULL,
    trf_district        TEXT,
    active              BOOLEAN DEFAULT true,
    default_max_minutes INTEGER,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    base_id             TEXT REFERENCES public.bases(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    org_id              BIGINT NOT NULL REFERENCES public.organizations(id)
);

-- 6. stops — original table; renamed to stops_legacy in 20251222_phase5c_convert_stops_RO_compat_view.sql
--    asset_id is a plain column (no FK enforced at the DB level)
CREATE TABLE IF NOT EXISTS public.stops (
    "STOP_ID"                    TEXT PRIMARY KEY,
    "TRF_DISTRICT_CODE"          TEXT,
    "BAY_CODE"                   TEXT,
    "BEARING_CODE"               TEXT,
    "ON_STREET_NAME"             TEXT,
    "INTERSECTION_LOC"           TEXT,
    "HASTUS_CROSS_STREET_NAME"   TEXT,
    "KCM_MANAGED_EQUIPMENT"      TEXT,
    "ROUTE_LIST"                 TEXT,
    "NUM_SHELTERS"               INTEGER,
    "STOP_STATUS"                TEXT,
    "GISOBJID"                   TEXT,
    lon        DOUBLE PRECISION,
    lat        DOUBLE PRECISION,
    is_hotspot BOOLEAN DEFAULT false,
    compactor  BOOLEAN DEFAULT false,
    has_trash  BOOLEAN DEFAULT false,
    notes      TEXT,
    pool_id    TEXT,
    asset_id   BIGINT
    -- last_level3_at added by 20251202_intelligence_foundation.sql
    -- priority_class + constraints added by 20251212_add_stops.priorityclass.sql
);

-- 7. route_runs — depends on organizations (nullable), bases (nullable), route_pools (nullable)
--    org_id is nullable here; NOT NULL enforcement added by 20260513_r11_route_runs_org_notnull.sql
CREATE TABLE IF NOT EXISTS public.route_runs (
    id               BIGSERIAL PRIMARY KEY,
    user_id          BIGINT,
    route_pool_id    TEXT REFERENCES public.route_pools(id),
    base_id          TEXT REFERENCES public.bases(id),
    run_date         DATE NOT NULL,
    status           TEXT NOT NULL DEFAULT 'planned',
    total_distance_m DOUBLE PRECISION,
    total_duration_s DOUBLE PRECISION,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at       TIMESTAMPTZ,
    finished_at      TIMESTAMPTZ,
    org_id           BIGINT
    -- org_id NOT NULL + FK to organizations added by 20260513_r11_route_runs_org_notnull.sql
    -- assigned_user_oid added by 20251223_assign_user_oid_route_runs.sql (via 001_route_run_identity)
    -- created_by_oid added by 20251223_assign_user_oid_route_runs.sql (via 001_route_run_identity)
);

-- 8. route_run_stops — depends on route_runs, stops, assets
--    stop_id FK references stops("STOP_ID"); replaced by transit_stops in 20251222_phase5c_FK_transfer_transit_stops.sql
CREATE TABLE IF NOT EXISTS public.route_run_stops (
    id               BIGSERIAL PRIMARY KEY,
    route_run_id     BIGINT NOT NULL REFERENCES public.route_runs(id) ON DELETE CASCADE,
    stop_id          TEXT NOT NULL REFERENCES public.stops("STOP_ID"),
    sequence         INTEGER NOT NULL,
    planned_distance_m DOUBLE PRECISION,
    planned_duration_s DOUBLE PRECISION,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    status           TEXT NOT NULL DEFAULT 'pending'
                       CONSTRAINT route_run_stops_status_check
                       CHECK (status = ANY (ARRAY['pending','in_progress','done','skipped'])),
    completed_at     TIMESTAMPTZ,
    asset_id         BIGINT NOT NULL REFERENCES public.assets(id),
    started_at       TIMESTAMPTZ
    -- trash_volume, hazard_id, infra_issue_id added by 20251202_intelligence_foundation.sql
    -- origin_type + constraint + index added by 20251212_add_routr_run_stops.origin_type.sql
);

-- 9. clean_logs — depends on route_run_stops (nullable), stops
--    stop_id FK references stops("STOP_ID"); replaced by transit_stops in phase5c
CREATE TABLE IF NOT EXISTS public.clean_logs (
    id                BIGSERIAL PRIMARY KEY,
    route_run_stop_id BIGINT REFERENCES public.route_run_stops(id),
    stop_id           TEXT NOT NULL REFERENCES public.stops("STOP_ID"),
    user_id           BIGINT,
    cleaned_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    duration_minutes  INTEGER,
    picked_up_litter  BOOLEAN DEFAULT false,
    emptied_trash     BOOLEAN DEFAULT false,
    washed_shelter    BOOLEAN DEFAULT false,
    washed_pad        BOOLEAN DEFAULT false,
    level             SMALLINT,
    notes             TEXT,
    photo_keys        TEXT[],
    asset_id          BIGINT
    -- washed_can added by 20251216_add_washed_can.sql
    -- visit_id + FK added by 20251227_add_visitID_public_clean_logs.sql
);

-- 10. stop_risk_snapshot — depends on stops
--     stop_id FK references stops("STOP_ID"); replaced by transit_stops in phase5c
CREATE TABLE IF NOT EXISTS public.stop_risk_snapshot (
    stop_id                TEXT     PRIMARY KEY REFERENCES public.stops("STOP_ID"),
    is_hotspot             BOOLEAN  NOT NULL DEFAULT false,
    days_since_last_l3     INTEGER,
    recent_trash_volume_avg NUMERIC(4,2),
    last_hazard_at         TIMESTAMP,
    last_hazard_severity   INTEGER,
    infra_issue_score      NUMERIC(4,2),
    cleanliness_score      NUMERIC(4,2),
    safety_score           NUMERIC(4,2),
    infrastructure_score   NUMERIC(4,2),
    combined_risk_score    NUMERIC(6,3),
    computed_at            TIMESTAMP NOT NULL DEFAULT now(),
    hotspot_weight         NUMERIC(4,2) NOT NULL DEFAULT 0,
    l3_urgency_weight      NUMERIC(4,2) NOT NULL DEFAULT 0,
    has_recent_hazard      BOOLEAN  NOT NULL DEFAULT false,
    hazard_days_ago        INTEGER,
    hazard_decay_factor    NUMERIC(4,2) NOT NULL DEFAULT 0,
    asset_id               BIGINT REFERENCES public.assets(id)
);

COMMIT;
