-- ============================================================================
-- NI-1 (REQUIRED) — seed core.observation_type_registry so a clean rebuild keeps
-- a FUNCTIONING normalizer. Resolves NI-4 in-pass.
-- 2026-06-28 — data/seed-live-only-config-pre-rebuild
--
-- THE MAKE-OR-BREAK CAPTURE (recon docs/audit/2026-06-27-clean-build-vs-live-diff.md,
-- item g/NI-1): NO migration anywhere INSERTs registry rows. The chain only ADDS
-- the §4.1 columns (20260614_canon_norm_step2) and UPDATEs ok_rule/severity_map by
-- obs_kind (20260614_step3, 20260617_p1_presence_passthrough) on PRESUMED-existing
-- rows. On a clean rebuild those UPDATEs hit an EMPTY registry (0 rows, no-op) ->
-- 0 registry rows -> the write-time normalizer (observationNormalizer.ts) finds no
-- rule and writes all-NULL normalized fields -> intelligence/dashboards that read
-- obs_kind/norm_status/norm_severity are dead. This migration restores the 30 rows.
--
-- These 30 rows are dumped VERBATIM from live (pg_dump --column-inserts) — the exact
-- post-step3/post-passthrough FINAL state, values not reconstructed.
--
-- ── ORDERING (verified, no existing-migration surgery needed) ──────────────────
-- This file sorts AFTER every registry-mutating migration (step2 20260614 adds the
-- columns; step3 20260614 + p1 20260617 author the rules). On a clean build those
-- UPDATEs run first against the empty registry (harmless 0-row no-ops); THIS seed
-- then inserts the FINAL state directly. End state is correct without reordering or
-- modifying any existing migration. (Proven by clean-room rebuild — changelog.)
-- Depends on: core.asset_types(id=1) [20260628_seed_a_live_config] and
-- public.organizations(id=1) [20260627_issue013_seed_org1_tenant_uuid] — both FK
-- targets, both seeded earlier in the chain.
--
-- ── NI-4 DECISION — stop_not_serviced_due_to_safety has obs_kind = NULL: CORRECT ─
-- Determination: NULL is CORRECT, not a defect — seeded NULL verbatim.
-- Evidence:
--   1. CANONICAL_STATE_LAYER_DESIGN.md L136: stop_not_serviced_due_to_safety was
--      RETIRED and replaced by core.visits.outcome='skipped' + reason_code='safety'
--      — "a duplicate fact in a second table... two sources of truth for did this
--      stop get serviced." It is NOT modeled as an observation anymore.
--   2. Same doc L719-723 (RESOLVED 2026-05-25): it was "the one ambiguous row" that
--      does NOT fit the four-kind taxonomy (condition/action/measurement/presence)
--      and was retired for that reason. Assigning any kind would re-manufacture the
--      duplicate state the design eliminated (violates no-manufactured-state).
--   3. The row is is_active = false (retired/disabled); the write path does not
--      offer it for new observations.
--   4. observationNormalizer.ts handles a NULL obs_kind gracefully (obs_kind ??
--      null -> all-NULL normalized fields, never throws) — so the NULL cannot break
--      normalization.
-- Contrast: id=7 safety_concern_present is ALSO retired but keeps obs_kind='presence'
-- because it WAS a presence observation (superseded by more specific *_present types).
-- id=8 differs: it was replaced by a non-observation mechanism (the visit outcome),
-- so it has no kind. The NULL is semantically correct.
--
-- IDEMPOTENT: ON CONFLICT DO NOTHING (covers PK id and the (org_id, asset_type_id,
-- observation_key) unique) -> re-run / apply-to-live is a 0-row no-op. Runner records
-- the file so normal re-runs skip it. RLS: runner is fieldpro_admin (BYPASSRLS);
-- SET LOCAL app.current_org_id='1' lets the fail-closed WITH CHECK pass regardless.
-- ============================================================================

BEGIN;
SET LOCAL app.current_org_id = '1';

INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (7, 1, 1, 'safety_concern_present', 'Safety Concern Present (RETIRED — see specific *_present)', 'boolean', NULL, false, 100, false, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (9, 1, 1, 'encampment_present', 'Encampment Present', 'boolean', NULL, false, 120, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (10, 1, 1, 'fire_present', 'Fire Present', 'boolean', NULL, false, 130, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (11, 1, 1, 'dangerous_activity_present', 'Dangerous Activity Present', 'boolean', NULL, false, 140, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (12, 1, 1, 'drug_use_present', 'Drug Use Present', 'boolean', NULL, false, 150, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (13, 1, 1, 'violence_present', 'Violence Present', 'boolean', NULL, false, 160, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (6, 1, 1, 'trash_volume', 'Trash Volume', 'numeric', '{"max": 4, "min": 0}', false, 60, true, 'measurement', NULL, '{"lte": 1, "field": "level"}', '{"field": "level"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (55, 1, 1, 'picked_up_litter', 'Picked Up Litter', 'boolean', NULL, false, 45, true, 'action', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (56, 1, 1, 'emptied_trash', 'Emptied Trash', 'boolean', NULL, false, 46, true, 'action', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (57, 1, 1, 'washed_shelter', 'Washed Shelter', 'boolean', NULL, false, 47, true, 'action', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (58, 1, 1, 'washed_pad', 'Washed Pad', 'boolean', NULL, false, 48, true, 'action', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (5, 1, 1, 'washed_can', 'Washed Can', 'boolean', NULL, false, 50, true, 'action', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (8, 1, 1, 'stop_not_serviced_due_to_safety', 'Stop Not Serviced (RETIRED — see core.visits.outcome)', 'boolean', NULL, false, 110, false, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (61, 1, 1, 'spot_check', 'Spot Check (no work needed)', 'state', '["no_work_needed"]', false, 70, true, 'condition', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (14, 1, 1, 'biohazard_present', 'Biohazard Present', 'boolean', NULL, false, 170, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (15, 1, 1, 'access_blocked', 'Access Blocked', 'boolean', NULL, false, 180, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (16, 1, 1, 'other_safety_concern_present', 'Other Safety Concern', 'boolean', NULL, false, 190, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (17, 1, 1, 'infrastructure_issue_present', 'Infrastructure Issue Present', 'boolean', NULL, false, 200, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (1, 1, 1, 'ground_condition', 'Ground Condition', 'state', '["dirty", "clean"]', true, 10, true, 'condition', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (2, 1, 1, 'shelter_condition', 'Shelter Condition', 'state', '["dirty", "clean"]', true, 20, true, 'condition', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (3, 1, 1, 'pad_condition', 'Pad Condition', 'state', '["dirty", "clean"]', true, 30, true, 'condition', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (4, 1, 1, 'trash_can_condition', 'Trash Can Condition', 'state', '["has_trash", "empty"]', false, 40, true, 'condition', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (18, 1, 1, 'glass_damage_present', 'Glass Damage Present', 'boolean', NULL, false, 210, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (19, 1, 1, 'graffiti_present', 'Graffiti Present', 'boolean', NULL, false, 220, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (20, 1, 1, 'receptacle_damage_present', 'Receptacle Damage Present', 'boolean', NULL, false, 230, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (21, 1, 1, 'shelter_panel_damage_present', 'Shelter Panel Damage Present', 'boolean', NULL, false, 240, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (22, 1, 1, 'lighting_failure_present', 'Lighting Failure Present', 'boolean', NULL, false, 250, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (23, 1, 1, 'access_obstructed_by_landscape', 'Access Obstructed by Landscape', 'boolean', NULL, false, 260, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (24, 1, 1, 'structural_damage_present', 'Structural Damage Present', 'boolean', NULL, false, 270, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;
INSERT INTO core.observation_type_registry (id, org_id, asset_type_id, observation_key, display_name, value_type, valid_values, is_required, sort_order, is_active, obs_kind, payload_schema, ok_rule, severity_map) OVERRIDING SYSTEM VALUE VALUES (25, 1, 1, 'other_infrastructure_issue_present', 'Other Infrastructure Issue', 'boolean', NULL, false, 280, true, 'presence', '{"type": "object", "properties": {"severity": {"type": "integer", "minimum": 1}}, "additionalProperties": true}', NULL, '{"field": "severity"}') ON CONFLICT DO NOTHING;

COMMIT;
